import assert from "node:assert/strict";
import { mkdtemp, lstat, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { compileSpecsIr } from "./compile-spec-ir.mjs";
import {
  acquirePairLock,
  createPairMarker,
  PAIR_LOCK_NAME,
  writePairMarker,
} from "./spec-pair.mjs";
import {
  generateReferenceAudit,
  MAX_AUDIT_REPORT_BYTES,
  REFERENCE_AUDIT_TIMEOUT_MS,
  withReferenceAudit,
} from "./reference-audit-worker.mjs";

const pairLockPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "bundle",
  PAIR_LOCK_NAME,
);

async function withFixture(body, run) {
  const sourceRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-src-"));
  const irRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-ir-"));
  try {
    await writeFile(join(sourceRoot, "fixture.js"), body);
    await compileSpecsIr({ srcDir: sourceRoot, outDir: irRoot });
    await run({ sourceRoot, irRoot });
  } finally {
    await Promise.all([
      rm(sourceRoot, { recursive: true, force: true }),
      rm(irRoot, { recursive: true, force: true }),
    ]);
  }
}

const triggerFixture = `
export default {
  name: "fixture",
  args: { generators: { trigger: (search, previous) => search !== previous } },
};
`;

test("audit is generated by a fresh restricted child and returns full provenance", async () => {
  await withFixture(triggerFixture, async ({ sourceRoot, irRoot }) => {
    const report = await generateReferenceAudit({ sourceRoot, irRoot });
    assert.equal(report.ok, true);
    assert.ok(report.hookManifest.length > 0);
    assert.ok(report.sourceToIr.length > 0);
    assert.equal(report.reproducibility.algorithm, "sha256");
    assert.ok(MAX_AUDIT_REPORT_BYTES > JSON.stringify(report).length);
    assert.ok(REFERENCE_AUDIT_TIMEOUT_MS >= 1000);
  });
});

test("reference operation holds the pair lock through probes and final drift check", async () => {
  await withFixture(triggerFixture, async ({ sourceRoot, irRoot }) => {
    const irPath = join(irRoot, "fixture.json");
    const originalIr = await readFile(irPath, "utf8");
    await assert.rejects(
      withReferenceAudit({ sourceRoot, irRoot }, async () => {
        await assert.rejects(
          acquirePairLock(pairLockPath),
          /spec pair publication is already locked by pid/,
        );
        await writeFile(irPath, `${originalIr} \n`);
      }),
      /IR tree does not match \.spec-pair\.json|source\/IR pair changed/,
    );
    await writeFile(irPath, originalIr);
  });
});

test("a caller-supplied stale audit cannot be used", async () => {
  for (const field of ["audit", "auditPath", "probe", "sourceProbe", "moduleProbe", "unexpected"]) {
    await assert.rejects(
      generateReferenceAudit({ [field]: true }),
      new RegExp(
        field === "audit"
          ? "no longer accepts an audit report"
          : field === "auditPath"
            ? "no longer accepts auditPath"
            : `unknown field ${field}`,
      ),
    );
  }
});

test("permission-restricted audit rejects a malicious top-level touch", async () => {
  const sourceRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-evil-src-"));
  const irRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-evil-ir-"));
  const markerRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-marker-"));
  const marker = join(markerRoot, "audit-must-not-touch");
  try {
    // Compile a benign generation first so the test does not execute the
    // malicious module in the parent build process. Then keep the generated
    // pair and replace only the source with the hostile top-level module.
    await writeFile(join(sourceRoot, "fixture.js"), triggerFixture);
    await compileSpecsIr({ srcDir: sourceRoot, outDir: irRoot });
    const hostile = `
import { execFileSync } from "node:child_process";
execFileSync("/usr/bin/touch", [${JSON.stringify(marker)}]);
export default {
  name: "fixture",
  args: { generators: { trigger: (search, previous) => search !== previous } },
};
`;
    await writeFile(join(sourceRoot, "fixture.js"), hostile);
    await writePairMarker(
      irRoot,
      await createPairMarker({ sourceRoot, irRoot }),
    );

    await assert.rejects(
      generateReferenceAudit({ sourceRoot, irRoot }),
      /strict source\/IR audit failed|reference audit worker failed/,
    );
    await assert.rejects(lstat(marker), { code: "ENOENT" });
  } finally {
    await Promise.all([
      rm(sourceRoot, { recursive: true, force: true }),
      rm(irRoot, { recursive: true, force: true }),
      rm(markerRoot, { recursive: true, force: true }),
    ]);
  }
});

test("restricted audit rejects a raw backslash escape name before any import", async () => {
  const sourceRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-backslash-src-"));
  const irRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-backslash-ir-"));
  const marker = join(sourceRoot, "..", "audit-backslash-executed");
  try {
    await writeFile(join(sourceRoot, "fixture.js"), triggerFixture);
    await compileSpecsIr({ srcDir: sourceRoot, outDir: irRoot });
    await writeFile(
      join(sourceRoot, "..\\escape.js"),
      `import { writeFileSync } from "node:fs";
writeFileSync(${JSON.stringify(marker)}, "executed");
export default { name: "escape", args: [] };
`,
    );
    await writePairMarker(
      irRoot,
      await createPairMarker({ sourceRoot, irRoot }),
    );
    await assert.rejects(
      generateReferenceAudit({ sourceRoot, irRoot }),
      /literal backslash before normalization|strict source\/IR audit failed/,
    );
    await assert.rejects(lstat(marker), { code: "ENOENT" });
  } finally {
    await Promise.all([
      rm(sourceRoot, { recursive: true, force: true }),
      rm(irRoot, { recursive: true, force: true }),
    ]);
  }
});

test("restricted audit cannot read a secret beside the source root", async () => {
  const sourceRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-sibling-src-"));
  const irRoot = await mkdtemp(join(tmpdir(), "easy-complete-audit-sibling-ir-"));
  const sibling = join(sourceRoot, "..", "sibling-secret.js");
  const secret = "do-not-authorize-siblings\n";
  try {
    await writeFile(join(sourceRoot, "fixture.js"), triggerFixture);
    await compileSpecsIr({ srcDir: sourceRoot, outDir: irRoot });
    await writeFile(sibling, secret);
    await writeFile(
      join(sourceRoot, "fixture.js"),
      `import { readFileSync } from "node:fs";
readFileSync(new URL("../sibling-secret.js", import.meta.url), "utf8");
${triggerFixture}
`,
    );
    await writePairMarker(
      irRoot,
      await createPairMarker({ sourceRoot, irRoot }),
    );
    await assert.rejects(
      generateReferenceAudit({ sourceRoot, irRoot }),
      /strict source\/IR audit failed|reference audit worker failed|ERR_ACCESS_DENIED/,
    );
    assert.equal(await readFile(sibling, "utf8"), secret);
  } finally {
    await Promise.all([
      rm(sourceRoot, { recursive: true, force: true }),
      rm(irRoot, { recursive: true, force: true }),
      rm(sibling, { force: true }),
    ]);
  }
});
